(("default" . ((user-emacs-directory . "~/.config/chemacs/doom")))
 ("me"      . ((user-emacs-directory . "~/.config/chemacs/me")
               (server-name "me")))
 ("sandbox" . ((user-emacs-directory . "~/.config/chemacs/sandbox")
               (env . (("DOOMDIR" . "~/.config/chemacs/sandbox.doom")))
               (server-name "sandbox")))
 ("work"    . ((user-emacs-directory . "~/.config/chemacs/work")
               (env . (("DOOMDIR" . "~/.config/chemacs/work.doom")))
               (server-name "work"))))
